[project]
name = 'aibtcdev-smart-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

# external contracts loaded by clarinet

[[project.requirements]]
contract_id = 'SP2PABAF9FTAJYNFZH93XENAJ8FVY99RRM50D2JG9.nft-trait'

[[project.requirements]]
contract_id = 'SP3FBR2AGK5H9QBDH3EEN6DF8EK8JY7RX8QJ5SVTE.sip-010-trait-ft-standard'

[[project.requirements]]
contract_id = 'ST000000000000000000002AMW42H.pox-4'

# airdrop nft contracts

[contracts.aibtcdev-airdrop-1]
path = 'contracts/aibtcdev-airdrop-1.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-airdrop-2]
path = 'contracts/aibtcdev-airdrop-2.clar'
clarity_version = 2
epoch = 2.5

# dao base contract

[contracts.aibtcdev-dao]
path = 'contracts/dao/aibtcdev-dao.clar'
clarity_version = 2
epoch = 2.5

# dao proposals

[contracts.aibtc001-bootstrap]
path = 'contracts/dao/proposals/aibtc001-bootstrap.clar'
clarity_version = 2
epoch = 2.5

# dao extensions

[contracts.aibtcdev-bank-account]
path = 'contracts/dao/extensions/aibtcdev-bank-account.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-direct-execute]
path = 'contracts/dao/extensions/aibtcdev-direct-execute.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-messaging]
path = 'contracts/dao/extensions/aibtcdev-messaging.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-payments]
path = 'contracts/dao/extensions/aibtcdev-payments.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-treasury]
path = 'contracts/dao/extensions/aibtcdev-treasury.clar'
clarity_version = 2
epoch = 2.5

# dao traits

[contracts.aibtcdev-dao-v1]
path = 'contracts/dao/traits/aibtcdev-dao-v1.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-dao-traits-v1]
path = 'contracts/dao/traits/aibtcdev-dao-traits-v1.clar'
clarity_version = 2
epoch = 2.5

# testing utilities

[contracts.external-proxy]
path = 'contracts/test-proxy.clar'
deployer = 'wallet_1'
clarity_version = 2
epoch = 2.5

[contracts.proxy]
path = 'contracts/test-proxy.clar'
clarity_version = 2
epoch = 2.5

[contracts.test-proxy]
path = 'contracts/test-proxy.clar'
clarity_version = 2
epoch = 2.5
