[project]
name = 'aibtcdev-smart-contracts'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'

[[project.requirements]]
contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.nft-trait.nft-trait'

[[project.requirements]]
contract_id = 'ST1NXBK3K5YYMD6FD41MVNP3JS1GABZ8TRVX023PT.sip-010-trait-ft-standard'

[contracts.aibtc001-bootstrap]
path = 'contracts/dao/proposals/aibtc001-bootstrap.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-airdrop-1]
path = 'contracts/aibtcdev-airdrop-1.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-airdrop-2]
path = 'contracts/aibtcdev-airdrop-2.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-bank-account]
path = 'contracts/dao/extensions/aibtcdev-bank-account.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-dao]
path = 'contracts/dao/aibtcdev-dao.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-extension-trait]
path = 'contracts/dao/traits/aibtcdev-extension-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-messaging]
path = 'contracts/dao/extensions/aibtcdev-messaging.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-payment-traits]
path = 'contracts/dao/traits/aibtcdev-payment-traits.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-payments]
path = 'contracts/dao/extensions/aibtcdev-payments.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-proposal-trait]
path = 'contracts/dao/traits/aibtcdev-proposal-trait.clar'
clarity_version = 2
epoch = 2.5

[contracts.aibtcdev-treasury]
path = 'contracts/dao/extensions/aibtcdev-treasury.clar'
clarity_version = 2
epoch = 2.5

[contracts.external-proxy]
path = 'contracts/test-proxy.clar'
deployer = 'wallet_1'
clarity_version = 2
epoch = 2.5

[contracts.proxy]
path = 'contracts/test-proxy.clar'
clarity_version = 2
epoch = 2.5

[contracts.test-proxy]
path = 'contracts/test-proxy.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
