[project]
name = 'aibtcdev-smart-contracts'
telemetry = true
cache_dir = './.cache'
requirements = []

[contracts.stacks-m2m-aibtc]
path = 'src/stacks-m2m-aibtc.clar'
clarity_version = 2
epoch = 2.4

[contracts.stacks-m2m-trait-v1]
path = 'src/stacks-m2m-trait-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.stacks-m2m-v1]
path = 'src/stacks-m2m-v1.clar'
clarity_version = 2
epoch = 2.4

[contracts.stacks-m2m-v2]
path = 'src/stacks-m2m-v2.clar'
clarity_version = 2
epoch = 2.4

[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
