name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  # allow running manually
  workflow_dispatch:

jobs:
  test-contracts:
    name: "Test contracts with Clarinet"
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v3
      - name: "Check contract syntax"
        uses: docker://hirosystems/clarinet:latest
        with:
          args: check
      - name: "Execute unit tests"
        uses: docker://hirosystems/clarinet:latest
        with:
          args: test --coverage --manifest-path=./Clarinet.toml
      - name: "Upload code coverage"
        uses: codecov/codecov-action@v3
        with:
          files: ./coverage.lcov
          verbose: true